export const TOOLTIPS = {
  QUALIFYING_QUESTIONS: {
    IS_MILITARY: 'Lenders make low-priced loans available to our veterans and current members in active military service.',
    CREDIT_SCORE: 'These score estimates can be used to help estimate your rates. When you are ready to apply, we can pull a more precise credit score.',
    PROPERTY_VALUE: 'Just estimate this -- if you choose to apply, we\'ll ask for your complete address in order to determine a more accurate home appraisal based on 3rd parties.',
    PRIMARY_USE_OF_PROPERTY: 'Lenders have different loan products available for homes, whether they are used as a primary residence, secondary residence (e.g. vacation home), or for investment purposes.',
    LOAN_AMOUNT: 'This is the current mortgage balance you are seeking to refinance.',
    CASH_OUT_AMOUNT: 'When you refinance, you can also \'tap\' into the home equity you have built up. You can receive this equity as cash, which you in turn can use to pay off other debts, remodel your home, or use for other large expenses, such as college tuition. Any portion you cash out gets rolled into your new mortgage balance, though.',
    LOAN_TERM: 'This is your current mortgage loan\'s term. On a subsequent screen, you can sort and filter out different loan terms for the loan you are seeking.',
  },
  REVIEW_QUOTES_PAGE: {
    THIRTY_YEARS_FIXED: '30-year fixed rate mortgages have a 30 year (or, 360 month) term.',
    FIFTY_YEARS_FIXED: '15-year fixed rate mortgages have a 15 year (or, 180 month) term.',
    FIVE_TO_ONE_ARM: '5/1 Adjustable Rate mortgages have a fixed mortgage rate for the first 5 years. Then, on an annual basis, interest rates are adjusted. Given that rates are at historic lows, those interest rates will likely go up afer your first five years on this loan.',
    MONTHLY_PAYMENT: 'Your monthly payment includes principal and interest, but does not include taxes and homeowner insurance.',
    PRODUCT_NAME: 'The loan term and interest rate type (fixed or variable)',
    INTEREST_RATE: 'Your interest rate is the cost of borrowing the principal on the loan.',
    APR: 'The APR includes other charges or fees, such as closing costs, in calculating your monthly interest rate.',
    ESTIMATED_LENDER_FEES: 'These are the fees that your lender assesses. If they are third party fees (for example appraisal fees), these are excluded from this amount.',
    CLOSING_COSTS: 'Closing costs include all origination fees and additional fees associated with the loan settlement process.',
    // expanded quote view
    ORIGINATION_FEES_POINTS_PAID: 'These are the fees that your lender assesses. If they are third party fees (for example appraisal fees), these are excluded from this amount.',
    ORIGINATION_FEES_THIRD_PARTY: 'These include the cost of credit reports and appraisals.',
    ORIGINATION_FEES_OTHER_LENDER_FEES: 'Other *origination* fees the lender charges besides points paid',
    ADDITIONAL_FEES_APPRAISAL_FEES: 'Common across lenders\' offers',
    ADDITIONAL_FEES_TITLE_RECORDING_FEES: 'Common across lenders\' offers',
    ADDITIONAL_FEES_ESTIMATED_CLOSING_COSTS: 'Other closing costs that aren\'t origination fees that this specific lender charges.',
  },
  LOAN_OFFER_PAGE: {
    INTEREST_RATE: 'Of the upfront origination fees, how much represents what you will pay for a lower interest rate',
    TOTAL_INTEREST: 'Over the life of the loan, here\'s the total amount of interest you\'d pay.',
    ADDITIONAL_FEES_TITLE_RECORDING_FEES: 'Title insurance, tax service, escrow and other fees are passed directly through to the borrower',
    NUMBER_OF_PAYMENTS: 'The total number of payments you would make over the life of the loan',
    SCHEDULED_PAYMENT: 'Your scheduled monthly payment includes principal and interest, but does not include taxes and homeowner insurance.',
    LOAN_AMOUNT: 'This amount wil be loaned by the lender.',
    LOAN_TERM: 'Your loan term is how long the loan will last if you make the required minimum payments each month.',
  },
  PROPERTY_TYPE: 'Certain lenders restrict what kinds of property their loans are able to refinance. We use this information to find the right lender for your scenario.',
  SSN: 'We use the last 4 digits of your social security number along with your address to verify your identity.',
  IS_COBORROWER: 'If you own a home with your co-borrower and would like to include their income , assets and liabilities in applying for a loan, enter their information',
  RELATIONSHIP_TO_COBORROWER: 'Lenders use this information to understand more about your coborrower.',
  INCOME_TYPE: 'Lenders use income as a major determinant of your ability to make a loan\'s monthly payment.',
  INCOME_AMOUNT: 'Your annual gross income shoudl include base pay, commissions and any other stock-based compensation. Alimony may be included, to the extent that you want that income to be included in an underwriting decision.',
  EMPLOYER_NAME: 'This is used to verify employment and salary details. If possible, we wiill use third party data sources instead of asking you to submit pay stubs.',
  REAL_ESTATE_ASSETS: 'We match up your mortgage loans with other real estate assets you might have, in order to accurately determine your debt to income ratio.',
  COBORROWER_MOBILE_PHONE: 'Mobile phone numbers are used to verify your identity. We won\'t use this for marketing purposes unless we get your permission (and it\'s not required to use our service).',
};

export const SERVICE_CENTER_INFO = {
  PHONE_NUMBER: '(123) 456-7890',
  EMAIL_ADDRESS: 'help@refinance.com',
};

export const US_STATES = [
  { value: 'AL', label: 'AL' },
  { value: 'AK', label: 'AK' },
  { value: 'AZ', label: 'AZ' },
  { value: 'AR', label: 'AR' },
  { value: 'CA', label: 'CA' },
  { value: 'CO', label: 'CO' },
  { value: 'CT', label: 'CT' },
  { value: 'DC', label: 'DC' },
  { value: 'DE', label: 'DE' },
  { value: 'FL', label: 'FL' },
  { value: 'GA', label: 'GA' },
  { value: 'HI', label: 'HI' },
  { value: 'ID', label: 'ID' },
  { value: 'IL', label: 'IL' },
  { value: 'IN', label: 'IN' },
  { value: 'IA', label: 'IA' },
  { value: 'KS', label: 'KS' },
  { value: 'KY', label: 'KY' },
  { value: 'LA', label: 'LA' },
  { value: 'ME', label: 'ME' },
  { value: 'MD', label: 'MD' },
  { value: 'MA', label: 'MA' },
  { value: 'MI', label: 'MI' },
  { value: 'MN', label: 'MN' },
  { value: 'MS', label: 'MS' },
  { value: 'MO', label: 'MO' },
  { value: 'MT', label: 'MT' },
  { value: 'NE', label: 'NE' },
  { value: 'NV', label: 'NV' },
  { value: 'NH', label: 'NH' },
  { value: 'NJ', label: 'NJ' },
  { value: 'NM', label: 'NM' },
  { value: 'NY', label: 'NY' },
  { value: 'NC', label: 'NC' },
  { value: 'ND', label: 'ND' },
  { value: 'OH', label: 'OH' },
  { value: 'OK', label: 'OK' },
  { value: 'OR', label: 'OR' },
  { value: 'PA', label: 'PA' },
  { value: 'PR', label: 'PR' },
  { value: 'RI', label: 'RI' },
  { value: 'SC', label: 'SC' },
  { value: 'SD', label: 'SD' },
  { value: 'TN', label: 'TN' },
  { value: 'TX', label: 'TX' },
  { value: 'UT', label: 'UT' },
  { value: 'VT', label: 'VT' },
  { value: 'VA', label: 'VA' },
  { value: 'WA', label: 'WA' },
  { value: 'WV', label: 'WV' },
  { value: 'WI', label: 'WI' },
  { value: 'WY', label: 'WY' },
];
